import hre from "hardhat";
import fs from "fs";
import path from "path";

async function main() {
  console.log("Starting deployment...");

  const PraiseBoard = await hre.ethers.getContractFactory("PraiseBoard");
  const board = await PraiseBoard.deploy();
  
  await board.waitForDeployment();
  
  const address = await board.getAddress();
  console.log(`PraiseBoard deployed to: ${address}`);

  // Save the address to a config file for the frontend
  const configPath = path.join(__dirname, "..", "src", "contract-config.ts");
  const content = `// Auto-generated by Hardhat deploy script
export const CONTRACT_ADDRESS = "${address}";
`;
  
  fs.writeFileSync(configPath, content);
  console.log(`Saved contract address to ${configPath}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
