// Auto-generated by Hardhat deploy script
export const CONTRACT_ADDRESS = "0x9bABC0CE0a9f63E267C2DF2271e0c8642398c35f";

export const CONTRACT_ABI = [
  "event TipReceived(address indexed sender, uint256 amount, string note)",
  "function tip(string calldata note) external payable",
  "function withdraw() external",
  "function owner() view returns (address)"
];
