// Auto-generated by Hardhat deploy script
export const CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_CONTRACT_ADDRESS as string;

export const CONTRACT_ABI = [
  "event TipReceived(address indexed sender, uint256 amount, string note)",
  "function tip(string calldata note) external payable",
  "function withdraw() external",
  "function owner() view returns (address)"
];
